/**
 * Travel Conseriage
 * API for managing Travel Conceriage Service datasets.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ammar.haris@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TravelConseriage) {
      root.TravelConseriage = {};
    }
    root.TravelConseriage.ModelPackage = factory(root.TravelConseriage.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ModelPackage model module.
   * @module model/ModelPackage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelPackage</code>.
   * @alias module:model/ModelPackage
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>ModelPackage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelPackage} obj Optional instance to populate.
   * @return {module:model/ModelPackage} The populated <code>ModelPackage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('agencyId')) {
        obj['agencyId'] = ApiClient.convertToType(data['agencyId'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('destLat')) {
        obj['destLat'] = ApiClient.convertToType(data['destLat'], 'Number');
      }
      if (data.hasOwnProperty('destLong')) {
        obj['destLong'] = ApiClient.convertToType(data['destLong'], 'Number');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
      if (data.hasOwnProperty('adultPrice')) {
        obj['adultPrice'] = ApiClient.convertToType(data['adultPrice'], 'Number');
      }
      if (data.hasOwnProperty('childPrice')) {
        obj['childPrice'] = ApiClient.convertToType(data['childPrice'], 'Number');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('creationDate')) {
        obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
      }
      if (data.hasOwnProperty('createdBy')) {
        obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'Number');
      }
      if (data.hasOwnProperty('LastModificationDate')) {
        obj['LastModificationDate'] = ApiClient.convertToType(data['LastModificationDate'], 'Date');
      }
      if (data.hasOwnProperty('LastModifiedBy')) {
        obj['LastModifiedBy'] = ApiClient.convertToType(data['LastModifiedBy'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('isDeleted')) {
        obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} agencyId
   */
  exports.prototype['agencyId'] = undefined;
  /**
   * Package Name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Destination Latitude
   * @member {Number} destLat
   */
  exports.prototype['destLat'] = undefined;
  /**
   * Destination Longitude
   * @member {Number} destLong
   */
  exports.prototype['destLong'] = undefined;
  /**
   * Duration in Days
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {Number} adultPrice
   */
  exports.prototype['adultPrice'] = undefined;
  /**
   * @member {Number} childPrice
   */
  exports.prototype['childPrice'] = undefined;
  /**
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {Date} creationDate
   */
  exports.prototype['creationDate'] = undefined;
  /**
   * @member {Number} createdBy
   */
  exports.prototype['createdBy'] = undefined;
  /**
   * @member {Date} LastModificationDate
   */
  exports.prototype['LastModificationDate'] = undefined;
  /**
   * @member {Number} LastModifiedBy
   */
  exports.prototype['LastModifiedBy'] = undefined;
  /**
   * Package Status
   * @member {module:model/ModelPackage.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Boolean} isDeleted
   * @default false
   */
  exports.prototype['isDeleted'] = false;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "active"
     * @const
     */
    "active": "active",
    /**
     * value: "archived"
     * @const
     */
    "archived": "archived",
    /**
     * value: "pending"
     * @const
     */
    "pending": "pending"  };


  return exports;
}));


