/**
 * Travel Conseriage
 * API for managing Travel Conceriage Service datasets.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ammar.haris@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelPackage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelPackage'));
  } else {
    // Browser globals (root is window)
    if (!root.TravelConseriage) {
      root.TravelConseriage = {};
    }
    root.TravelConseriage.PackageApi = factory(root.TravelConseriage.ApiClient, root.TravelConseriage.ModelPackage);
  }
}(this, function(ApiClient, ModelPackage) {
  'use strict';

  /**
   * Package service.
   * @module api/PackageApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PackageApi. 
   * @alias module:api/PackageApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getInventory operation.
     * @callback module:api/PackageApi~getInventoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelPackage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns package inventories
     * Returns list of all packages
     * @param {module:api/PackageApi~getInventoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelPackage}
     */
    this.getInventory = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ModelPackage;

      return this.apiClient.callApi(
        '/package/inventory', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
