/**
 * Travel Conseriage
 * API for managing Travel Conceriage Service datasets.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ammar.haris@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TravelConseriage);
  }
}(this, function(expect, TravelConseriage) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TravelConseriage.Agent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Agent', function() {
    it('should create an instance of Agent', function() {
      // uncomment below and update the code to test Agent
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be.a(TravelConseriage.Agent);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be();
    });

    it('should have the property agencyId (base name: "agencyId")', function() {
      // uncomment below and update the code to test the property agencyId
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "LastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "Email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be();
    });

    it('should have the property mobile (base name: "Mobile")', function() {
      // uncomment below and update the code to test the property mobile
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be();
    });

    it('should have the property isDeleted (base name: "isDeleted")', function() {
      // uncomment below and update the code to test the property isDeleted
      //var instane = new TravelConseriage.Agent();
      //expect(instance).to.be();
    });

  });

}));
