/**
 * Travel Conseriage
 * API for managing Travel Conceriage Service datasets.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ammar.haris@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Agency', 'model/Agent', 'model/ApiResponse', 'model/ModelPackage', 'model/User', 'api/AgencyApi', 'api/AgentApi', 'api/PackageApi', 'api/UserApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Agency'), require('./model/Agent'), require('./model/ApiResponse'), require('./model/ModelPackage'), require('./model/User'), require('./api/AgencyApi'), require('./api/AgentApi'), require('./api/PackageApi'), require('./api/UserApi'));
  }
}(function(ApiClient, Agency, Agent, ApiResponse, ModelPackage, User, AgencyApi, AgentApi, PackageApi, UserApi) {
  'use strict';

  /**
   * API_for_managing_Travel_Conceriage_Service_datasets_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var TravelConseriage = require('index'); // See note below*.
   * var xxxSvc = new TravelConseriage.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new TravelConseriage.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new TravelConseriage.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new TravelConseriage.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Agency model constructor.
     * @property {module:model/Agency}
     */
    Agency: Agency,
    /**
     * The Agent model constructor.
     * @property {module:model/Agent}
     */
    Agent: Agent,
    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse: ApiResponse,
    /**
     * The ModelPackage model constructor.
     * @property {module:model/ModelPackage}
     */
    ModelPackage: ModelPackage,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The AgencyApi service constructor.
     * @property {module:api/AgencyApi}
     */
    AgencyApi: AgencyApi,
    /**
     * The AgentApi service constructor.
     * @property {module:api/AgentApi}
     */
    AgentApi: AgentApi,
    /**
     * The PackageApi service constructor.
     * @property {module:api/PackageApi}
     */
    PackageApi: PackageApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi
  };

  return exports;
}));
